"""User-facing AUTO_GPS training workflow for the Windows Compute Worker."""

COMPUTE_GPS_TRAINING_HMI = r'''
<style id="compute-gps-training-hmi-style">
#compute-gps-training-panel .cgt-grid{display:grid;grid-template-columns:1fr 1fr 120px;gap:8px}
#compute-gps-training-panel .cgt-field label{display:block;margin-bottom:5px}
#compute-gps-training-panel .cgt-field input,#compute-gps-training-panel .cgt-field select{width:100%}
#compute-gps-training-panel .cgt-progress{height:7px;margin-top:10px;border:1px solid var(--line);border-radius:3px;overflow:hidden;background:#0d1010}
#compute-gps-training-panel .cgt-progress>i{display:block;width:0;height:100%;background:var(--ok);transition:width .2s ease}
#compute-gps-training-panel .cgt-status{margin-top:8px;padding:9px 10px;border-left:3px solid rgba(255,255,255,.15);background:#121515;color:#9ba29e;font-size:9px;line-height:1.55;white-space:pre-wrap}
#compute-gps-training-panel .cgt-status.good{border-left-color:var(--ok)}#compute-gps-training-panel .cgt-status.warn{border-left-color:var(--warn)}#compute-gps-training-panel .cgt-status.bad{border-left-color:var(--bad)}
#compute-gps-training-panel .cgt-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:9px}
#compute-gps-training-panel .cgt-result-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;margin-top:9px;background:rgba(255,255,255,.07)}
#compute-gps-training-panel .cgt-result{padding:8px;background:#151818}#compute-gps-training-panel .cgt-result span{display:block;color:var(--muted);font-size:8px}#compute-gps-training-panel .cgt-result b{display:block;margin-top:4px;font:650 10px ui-monospace,monospace}
@media(max-width:760px){#compute-gps-training-panel .cgt-grid{grid-template-columns:1fr}#compute-gps-training-panel .cgt-result-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
<script>
(function(){
 const WORKER='http://127.0.0.1:8765';
 const grid=document.querySelector('#view-data .grid');if(!grid)return;
 const panel=document.createElement('div');panel.id='compute-gps-training-panel';panel.className='panel span12';panel.innerHTML=`
  <h2>GPS AI 모델 학습</h2>
  <p class="sectionnote">GPS/RTK ON으로 같은 경로를 사람이 반복 주행한 RECORD 3개 이상을 선택하세요. 기준 Route는 RTK FIXED만으로 만들고, AI 학습은 RTK FIXED와 품질 조건을 통과한 RTK FLOAT/DGPS 구간을 사용합니다. 실제 AUTO_GPS 주행은 계속 RTK FIXED가 필수입니다.</p>
  <div class="cgt-grid">
   <div class="cgt-field"><label>정규화 GPS Route</label><select id="cgt-route"></select></div>
   <div class="cgt-field"><label>새 GPS 모델 이름</label><input id="cgt-model-id" placeholder="swing-gps-v1"></div>
   <div class="cgt-field"><label>Epoch</label><input id="cgt-epochs" type="number" min="1" max="60" value="30"></div>
  </div>
  <div id="cgt-selection" class="cgt-status">위 RECORD 목록에서 GPS 학습 기록을 선택하세요.</div>
  <div id="cgt-quality" class="cgt-status">GPS 학습 품질을 확인할 RECORD와 Route를 선택하세요.</div>
  <div class="cgt-progress"><i id="cgt-progress-bar"></i></div>
  <div id="cgt-job-status" class="cgt-status">GPS 학습 대기 중</div>
  <div id="cgt-result"></div>
  <div class="cgt-actions"><button id="cgt-start" class="primary">GPS 모델 학습 시작</button><button id="cgt-cancel" disabled>학습 취소</button><span id="cgt-worker" class="pill">Compute Worker 확인 중</span></div>`;
 grid.appendChild(panel);
 const el=id=>document.getElementById(id);let currentJob=null,polling=false,workerStatus=null,gpsStatus=null,qualityPreview=null,qualitySignature='',qualityLoading=false;
 const selected=()=>[...document.querySelectorAll('.rec-ai:checked')].map(x=>x.value);
 const errText=e=>String(e?.message||e||'알 수 없는 오류');
 const pct=v=>`${(Math.max(0,Math.min(1,Number(v)||0))*100).toFixed(1)}%`;
 async function fetchJson(url,options={}){const r=await fetch(url,{cache:'no-store',...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
 function roverPost(path,body){return fetchJson(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
 function workerPost(path,body){return fetchJson(WORKER+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
 function phaseName(v){return ({QUEUED:'대기',SYNCING:'RECORD 동기화',SYNCING_ROUTE:'GPS Route 동기화',BUILDING_GPS_DATASET:'GPS 품질·센서 정렬',GPS_TRAINING:'GPS AI 학습',GPS_EVALUATING:'GPS 고정 검증구간 평가',GPS_EXPORTING:'GPS ONNX 변환·검증',READY_TO_INSTALL:'차량 등록 준비',SUCCEEDED:'완료',FAILED:'실패',CANCELED:'취소'}[v]||v||'처리 중')}
 function defaultName(){if(el('cgt-model-id').value.trim())return;const d=new Date(),p=n=>String(n).padStart(2,'0');el('cgt-model-id').value=`swing-gps-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}`}
 function statusCount(map,key){return Number((map||{})[key]||0)}
 function renderQuality(){const box=el('cgt-quality');if(qualityLoading){box.className='cgt-status warn';box.textContent='선택한 RECORD의 GPS FIX/HDOP와 기준 Route 거리를 확인하는 중…';return}if(!qualityPreview){box.className='cgt-status';box.textContent='GPS 학습 품질을 확인할 RECORD와 Route를 선택하세요.';return}if(qualityPreview.error){box.className='cgt-status bad';box.textContent=`GPS 학습 품질 확인 실패 · ${qualityPreview.error}`;return}const a=qualityPreview.aggregate||{},eligible=Number(a.eligible_frames||0),total=Number(a.camera_frames||0),conditional=Number(a.conditional_eligible_frames||0),fixed=statusCount(a.eligible_by_status,'RTK FIXED'),float=statusCount(a.eligible_by_status,'RTK FLOAT'),dgps=statusCount(a.eligible_by_status,'DGPS FIX');const lines=[`GPS 기준 학습 가능 ${eligible.toLocaleString()} / ${total.toLocaleString()} frames (${pct(a.eligibility_ratio)})`,`채택 · RTK FIXED ${fixed.toLocaleString()} · RTK FLOAT ${float.toLocaleString()} · DGPS ${dgps.toLocaleString()} · 조건부 채택 합계 ${conditional.toLocaleString()}`,`제외 ${Number(a.excluded_frames||0).toLocaleString()} · 원본 GNSS 중 RTK FIXED ${pct(a.rtk_fixed_raw_ratio)}`,`조건부 기준 · HDOP ≤ ${Number(qualityPreview.training_policy?.maximum_conditional_hdop||1.5).toFixed(1)} · Route 거리 ≤ ${Number(qualityPreview.training_policy?.maximum_conditional_route_deviation_m||1.5).toFixed(1)} m`];for(const s of qualityPreview.sessions||[]){const raw=s.raw_status_counts||{},rawTotal=Number(s.gnss_rows||0),rFixed=statusCount(raw,'RTK FIXED'),rFloat=statusCount(raw,'RTK FLOAT'),rDgps=statusCount(raw,'DGPS FIX');lines.push(`${s.session} · 학습가능 ${Number(s.eligible_frames||0).toLocaleString()}/${Number(s.camera_frames||0).toLocaleString()} (${pct(s.eligibility_ratio)}) · GNSS FIXED/FLOAT/DGPS ${rFixed}/${rFloat}/${rDgps} of ${rawTotal}`)}lines.push('※ 이 수치는 GPS 조건 통과 예상치입니다. LiDAR·IMU·카메라·조작 라벨 필터 후 실제 학습 프레임은 더 줄 수 있습니다.');box.className=`cgt-status ${eligible>0?'good':'bad'}`;box.textContent=lines.join('\n')}
 async function requestQuality(records,route){const normalized=[...records].sort(),signature=JSON.stringify([route,...normalized]);if(!route||!records.length){qualitySignature='';qualityPreview=null;qualityLoading=false;renderQuality();return}if(signature===qualitySignature&&(qualityLoading||qualityPreview))return;qualitySignature=signature;qualityPreview=null;qualityLoading=true;renderQuality();try{qualityPreview=await roverPost('/api/v2/compute/gps-quality',{sessions:records,route_id:route})}catch(e){qualityPreview={error:errText(e)}}finally{qualityLoading=false;renderQuality();syncSelection(false)}}
 async function refreshGps(){try{gpsStatus=await fetchJson('/api/v2/gps-ai');const before=el('cgt-route').value;const routes=gpsStatus.routes||[];el('cgt-route').innerHTML=routes.length?routes.map(r=>`<option value="${r.route_id}">${r.route_id} · ${r.point_count||0} points</option>`).join(''):'<option value="">먼저 GPS Route를 생성하세요</option>';if(routes.some(r=>r.route_id===before))el('cgt-route').value=before;else if(gpsStatus.selected?.route_id&&routes.some(r=>r.route_id===gpsStatus.selected.route_id))el('cgt-route').value=gpsStatus.selected.route_id}catch(e){gpsStatus=null;el('cgt-route').innerHTML='<option value="">GPS Route 상태 확인 실패</option>'}syncSelection()}
 async function checkWorker(){try{workerStatus=await fetchJson(WORKER+'/api/v1/status');const base=!!workerStatus.capabilities?.gps_conditioned_training,ok=base&&!!workerStatus.capabilities?.gps_conditional_fix_training;el('cgt-worker').textContent=ok?`${workerStatus.hostname||'PC'} · GPS 품질 학습 준비됨`:base?'Worker GPS 정책 업데이트 필요':'Worker 업데이트 필요';el('cgt-worker').className=`pill ${ok?'good':'warn'}`}catch(e){workerStatus=null;el('cgt-worker').textContent='Compute Worker 미연결';el('cgt-worker').className='pill warn'}syncSelection()}
 function syncSelection(loadQuality=true){const records=selected(),route=el('cgt-route').value,gpsZero=!!qualityPreview?.aggregate&&Number(qualityPreview.aggregate.eligible_frames||0)<=0,workerReady=!!workerStatus?.capabilities?.gps_conditioned_training&&!!workerStatus?.capabilities?.gps_conditional_fix_training,ready=workerReady&&records.length>=3&&!!route&&!currentJob&&!gpsZero;el('cgt-selection').textContent=`${records.length}개 RECORD 선택됨 · ${route?`Route ${route}`:'정규화 Route 필요'} · Route/실주행은 RTK FIXED 전용 · 학습만 품질 통과 RTK FLOAT/DGPS를 추가 허용합니다.`;el('cgt-selection').className=`cgt-status ${records.length>=3&&route?'good':'warn'}`;el('cgt-start').disabled=!ready;if(loadQuality)requestQuality(records,route)}
 function finalQualityText(q){if(!q||!Number(q.candidate_frames||0))return '';const accepted=Number(q.accepted_frames||0),candidate=Number(q.candidate_frames||0),by=q.accepted_by_status||{};return `\n실제 GPS 채택 ${accepted.toLocaleString()}/${candidate.toLocaleString()} (${pct(q.eligibility_ratio)}) · FIXED ${statusCount(by,'RTK FIXED')} · FLOAT ${statusCount(by,'RTK FLOAT')} · DGPS ${statusCount(by,'DGPS FIX')}`}
 function renderResult(job,installed){const result=job?.result||{},ev=result.evaluation_summary||{},sync=result.sync||{},gpsQuality=result.gps_quality_summary||{};const steering=Number(ev.steering_mae_degrees),throttle=Number(ev.throttle_mae);el('cgt-result').innerHTML=`<div class="cgt-result-grid"><div class="cgt-result"><span>GPS 후보 모델</span><b>${result.model_id||'-'}</b></div><div class="cgt-result"><span>Route</span><b>${result.route_id||'-'}</b></div><div class="cgt-result"><span>조향 MAE</span><b>${Number.isFinite(steering)?steering.toFixed(2)+'°':'-'}</b></div><div class="cgt-result"><span>스로틀 MAE</span><b>${Number.isFinite(throttle)?throttle.toFixed(3):'-'}</b></div></div><div class="cgt-status ${installed?'good':'warn'}">${installed?'차량에 route-bound TRAINED GPS 후보 모델로 등록했습니다.':'GPS 학습은 완료됐지만 차량 등록 상태를 확인하세요.'}${finalQualityText(gpsQuality)}\n전송 ${(Number(sync.transferred_bytes||0)/1048576).toFixed(1)} MB · PC 캐시 재사용 ${(Number(sync.reused_bytes||0)/1048576).toFixed(1)} MB</div>`}
 async function start(){const sessions=selected(),routeId=el('cgt-route').value,modelId=el('cgt-model-id').value.trim(),epochs=Math.max(1,Math.min(60,Number(el('cgt-epochs').value)||30));if(sessions.length<3)return alert('GPS 학습은 RECORD 3개 이상이 필요합니다.');if(!routeId)return alert('정규화 GPS Route를 선택하세요.');if(qualityPreview?.aggregate&&Number(qualityPreview.aggregate.eligible_frames||0)<=0)return alert('현재 선택에는 GPS 조건을 통과하는 학습 프레임이 없습니다.');if(!modelId)return alert('새 GPS 모델 이름을 입력하세요.');if(!workerStatus?.capabilities?.gps_conditioned_training||!workerStatus?.capabilities?.gps_conditional_fix_training)return alert('Compute Worker를 최신 코드로 업데이트해 주세요. 새 GPS FIX 품질 학습 정책이 필요합니다.');el('cgt-start').disabled=true;el('cgt-result').innerHTML='';el('cgt-job-status').className='cgt-status warn';el('cgt-job-status').textContent='차량에서 GPS 학습 데이터/Route 전송 권한을 준비하는 중…';try{const transfer=await roverPost('/api/v2/compute/gps-transfer',{sessions,route_id:routeId});const job=await workerPost('/api/v1/jobs',{kind:'train_gps_rover_records',rover_url:location.origin,transfer_token:transfer.token,model_id:modelId,route_id:routeId,sessions,epochs});currentJob=job.job_id;el('cgt-cancel').disabled=false;polling=true;poll()}catch(e){currentJob=null;el('cgt-job-status').className='cgt-status bad';el('cgt-job-status').textContent='GPS 학습 시작 실패 · '+errText(e);syncSelection()}}
 async function poll(){if(!currentJob||!polling)return;try{const job=await fetchJson(WORKER+'/api/v1/jobs/'+currentJob);el('cgt-progress-bar').style.width=`${Math.round(Number(job.progress||0)*100)}%`;el('cgt-job-status').className=`cgt-status ${job.state==='FAILED'?'bad':job.state==='SUCCEEDED'?'good':'warn'}`;el('cgt-job-status').textContent=`${phaseName(job.phase)} · ${Math.round(Number(job.progress||0)*100)}%\n${job.message||''}`;if(job.state==='SUCCEEDED'){polling=false;let installed=false;try{await roverPost('/api/v2/compute/gps-model/install',{worker_urls:job.worker_urls||job.result?.worker_urls||workerStatus?.advertise_urls||[],job_id:job.job_id,model_id:job.result?.model_id,route_id:job.result?.route_id,artifact_token:job.artifact_token});installed=true;if(typeof refresh==='function')await refresh();await refreshGps()}catch(e){console.warn(e);el('cgt-job-status').textContent+='\n차량 GPS 후보 등록 실패: '+errText(e)}renderResult(job,installed);currentJob=null;el('cgt-cancel').disabled=true;syncSelection();return}if(job.state==='FAILED'||job.state==='CANCELED'){polling=false;currentJob=null;el('cgt-cancel').disabled=true;el('cgt-job-status').className='cgt-status bad';el('cgt-job-status').textContent=`${phaseName(job.phase)}\n${job.error||job.message||''}`;syncSelection();return}}catch(e){el('cgt-job-status').textContent='Worker 상태 확인 실패 · '+errText(e)}setTimeout(poll,1000)}
 el('cgt-start').onclick=start;el('cgt-cancel').onclick=async()=>{if(!currentJob)return;try{await fetchJson(WORKER+'/api/v1/jobs/'+currentJob,{method:'DELETE'});el('cgt-job-status').textContent='GPS 학습 취소 요청을 보냈습니다.'}catch(e){alert(errText(e))}};el('cgt-route').onchange=()=>{qualitySignature='';qualityPreview=null;syncSelection()};document.addEventListener('change',e=>{if(e.target?.classList?.contains('rec-ai'))syncSelection()});defaultName();refreshGps();checkWorker();setInterval(()=>{if(!currentJob){checkWorker();refreshGps()}syncSelection()},4000);
})();
</script>
'''.encode('utf-8')

__all__ = ["COMPUTE_GPS_TRAINING_HMI"]
