"""Single user-facing dashboard for Autonomy V2.

The legacy backend APIs remain available for hardware compatibility, but this
page is the only operator dashboard. Deprecated AUTO_ROUTE/AUTO_HYBRID controls
are intentionally not exposed.
"""

UNIFIED_DASHBOARD_HTML = r'''<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SWING Rover · Autonomy V2</title>
<style>
:root{color-scheme:dark;--bg:#0a0d0b;--panel:#131814;--panel2:#181f19;--line:#303a32;--text:#eef3ee;--muted:#929d94;--accent:#b6d59b;--ok:#9bd17f;--warn:#e1c278;--bad:#ff8594}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}button,input,select,textarea{font:inherit}button,input,select,textarea{background:#202820;color:var(--text);border:1px solid #465248;border-radius:8px;padding:9px}button{cursor:pointer;font-weight:750}button:hover:not(:disabled){border-color:var(--accent)}button:disabled{opacity:.45;cursor:not-allowed}.primary{border-color:#64835b;background:#263522}.danger{border-color:#873c49;background:#35151b;color:#ffb0bb}.warnbtn{border-color:#7b6332;background:#302916;color:#efd18a}.ghost{background:transparent}.good{color:var(--ok)!important}.warn{color:var(--warn)!important}.bad{color:var(--bad)!important}.muted{color:var(--muted)}
header{position:sticky;top:0;z-index:20;background:#090c0aec;border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}.top{height:58px;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 16px}.brand{display:flex;align-items:center;gap:10px}.brand img{width:32px;max-height:28px;object-fit:contain}.brand b{font-size:13px;letter-spacing:.1em}.brand small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.headstate{font:700 11px ui-monospace,monospace;color:var(--accent)}nav{display:flex;gap:4px;overflow-x:auto;padding:0 12px 8px}nav button{white-space:nowrap;min-height:32px;padding:6px 10px;font-size:10px;background:#101511}nav button.active{border-color:var(--accent);color:var(--accent);background:#182318}
main{max-width:1450px;margin:auto;padding:14px}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:10px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:13px;min-width:0}.panel h2,.panel h3{margin:0 0 9px}.panel h2{font-size:14px}.panel h3{font-size:12px}.span12{grid-column:span 12}.span8{grid-column:span 8}.span7{grid-column:span 7}.span6{grid-column:span 6}.span5{grid-column:span 5}.span4{grid-column:span 4}.span3{grid-column:span 3}.cards{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.stat{background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:10px}.stat span{display:block;color:var(--muted);font-size:9px;letter-spacing:.08em}.stat strong{display:block;margin-top:5px;font:750 12px ui-monospace,monospace;overflow:hidden;text-overflow:ellipsis}.modes{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.mode{background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:11px;display:flex;flex-direction:column;min-height:155px}.mode.active{border-color:var(--accent);box-shadow:0 0 0 1px #b6d59b33 inset}.mode b{font-size:12px}.mode p{color:var(--muted);font-size:10px;line-height:1.5;flex:1}.row{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.row>*{min-width:110px}.actions{display:flex;gap:7px;flex-wrap:wrap}.actions button{min-height:38px}.camera{width:100%;aspect-ratio:16/9;background:#020302;border:1px solid var(--line);border-radius:10px;object-fit:cover}.statusbox,pre{margin:0;white-space:pre-wrap;word-break:break-word;font:10px ui-monospace,monospace;color:var(--muted);background:#0c110d;border:1px solid #273128;border-radius:8px;padding:9px;max-height:330px;overflow:auto}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:7px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{color:var(--muted);font-size:9px}.sectionnote{font-size:10px;line-height:1.5;color:var(--muted);margin:0 0 10px}.split{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sensorgrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.sensor{border:1px solid var(--line);border-radius:9px;padding:9px;background:var(--panel2)}.sensor span{display:block;color:var(--muted);font-size:9px}.sensor strong{display:block;margin-top:5px;font:750 11px ui-monospace,monospace}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font:700 9px ui-monospace,monospace;color:var(--muted)}label{font-size:10px;color:var(--muted)}input[type=checkbox]{min-width:auto}.footer-note{font-size:9px;color:var(--muted);text-align:center;margin:14px}
@media(max-width:1050px){.span8,.span7,.span6,.span5,.span4,.span3{grid-column:span 12}.cards{grid-template-columns:repeat(3,minmax(0,1fr))}.sensorgrid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){main{padding:8px}.modes,.cards,.split,.sensorgrid{grid-template-columns:1fr}.top{padding:0 10px}.headstate{display:none}}
</style>
</head>
<body>
<header><div class="top"><div class="brand"><img src="/assets/swing-logo-white.png" onerror="this.style.display='none'"><div><b>SWING ROVER · AUTONOMY V2</b><small>단일 운영 대시보드 · 6 DRIVE MODES</small></div></div><div id="head-mode" class="headstate">CONNECTING</div></div><nav id="nav"><button data-view="drive">DRIVE</button><button data-view="data">DATA / AI</button><button data-view="gps">GPS AI</button><button data-view="local">LOCAL MAP</button><button data-view="hardware">HARDWARE</button><button data-view="system">SYSTEM</button><button data-view="debug">DEBUG</button></nav></header>
<main>
<section id="view-drive" class="view">
 <div class="grid">
  <div class="panel span12"><div class="cards"><div class="stat"><span>MODE</span><strong id="st-mode">-</strong></div><div class="stat"><span>RECORD</span><strong id="st-record">-</strong></div><div class="stat"><span>GPS AI</span><strong id="st-gps">-</strong></div><div class="stat"><span>LOCAL</span><strong id="st-local">-</strong></div><div class="stat"><span>AI MODEL</span><strong id="st-ai">-</strong></div><div class="stat"><span>SAFETY</span><strong id="st-safety">-</strong></div></div></div>
  <div class="panel span7"><div class="modes">
   <div class="mode" data-card="MANUAL"><b>1 · MANUAL</b><p>완전 수동. 자동 차선/일반 장애물/사람 개입 없이 hard safety만 유지합니다.</p><button data-mode="MANUAL" class="primary">MANUAL</button></div>
   <div class="mode" data-card="RECORD"><b>2 · RECORD</b><p>사람이 운전하면서 학습 데이터를 기록합니다.</p><label><input type="checkbox" id="record-gps"> GPS/RTK 기록</label><button data-mode="RECORD" class="primary">RECORD</button></div>
   <div class="mode" data-card="AUTO_AI"><b>3 · AUTO_AI</b><p>Camera + LiDAR + IMU 학습모델이 GPS 없이 직접 운전합니다.</p><button data-mode="AUTO_AI">AUTO_AI</button></div>
   <div class="mode" data-card="AUTO_GPS"><b>4 · AUTO_GPS</b><p>GPS ON RECORD에서 만든 정규화 Route와 GPS-conditioned AI 모델로 운전합니다.</p><button data-mode="AUTO_GPS">AUTO_GPS</button></div>
   <div class="mode" data-card="AUTO_LOCAL"><b>5 · AUTO_LOCAL</b><p>저장 LOCAL map + LiDAR/IMU localization + 목적지 경로로 운전합니다.</p><button data-mode="AUTO_LOCAL">AUTO_LOCAL</button></div>
   <div class="mode" data-card="AUTO"><b>6 · AUTO</b><p>준비된 GPS AI → LOCAL → 독립 AI 순으로 안전한 전략을 자동 선택합니다.</p><button data-mode="AUTO" class="primary">AUTO</button></div>
  </div><div class="actions" style="margin-top:10px"><button id="disarm" class="warnbtn">STOP / DISARM</button><button id="estop" class="danger">EMERGENCY STOP</button><button id="reset-safety">SAFETY RESET</button><button id="refresh">REFRESH</button></div></div>
  <div class="panel span5"><h2>LIVE CAMERA</h2><img class="camera" src="/stream.mjpg"><div id="drive-note" class="statusbox" style="margin-top:8px">loading...</div></div>
 </div>
</section>
<section id="view-data" class="view"><div class="grid">
 <div class="panel span8"><h2>RECORD SESSIONS</h2><p class="sectionnote">AUTO_AI Dataset은 human RECORD만 사용합니다. GPS ON 기록도 GPS를 제외하면 AUTO_AI Dataset에 사용할 수 있습니다.</p><div class="tablewrap"><table><thead><tr><th></th><th>SESSION</th><th>LABEL</th><th>SIZE</th><th>GPS</th></tr></thead><tbody id="record-rows"></tbody></table></div><div class="row" style="margin-top:8px"><input id="dataset-id" placeholder="dataset_id"><button id="dataset-build" class="primary">선택 RECORD → AUTO_AI Dataset</button></div></div>
 <div class="panel span4"><h2>DATASET</h2><pre id="dataset-status">-</pre></div>
 <div class="panel span6"><h2>AUTO_AI MODELS</h2><p class="sectionnote">GPS route에 묶이지 않는 일반 AUTO_AI 모델만 표시합니다.</p><div class="row"><select id="ai-model"></select><button id="ai-select">선택</button></div><div class="row" style="margin-top:8px"><select id="ai-stage"><option>TRAINED</option><option>OFFLINE_VALIDATED</option><option>CLOSED_AREA_VALIDATED</option><option>AUTO_ALLOWED</option></select><button id="ai-stage-set">Lifecycle 변경</button></div><pre id="ai-model-status" style="margin-top:8px">-</pre></div>
 <div class="panel span6"><h2>AUTO ENVIRONMENT</h2><p class="sectionnote">상위 AUTO가 독립 AUTO_AI를 선택할 때 사용하는 환경 태그입니다. 빈 태그는 AI fallback을 허용하지 않습니다.</p><div class="row"><input id="env-tags" placeholder="indoor,warehouse"><button id="env-save">환경 저장</button></div><pre id="auto-selector" style="margin-top:8px">-</pre></div>
</div></section>
<section id="view-gps" class="view"><div class="grid">
 <div class="panel span7"><h2>GPS ON RECORD → NORMALIZED ROUTE</h2><p class="sectionnote">같은 방향/같은 코스를 여러 번 기록한 RTK FIXED 세션을 선택합니다. 이상치 제거·방향정렬·중앙 경로 융합·smoothing/resampling을 수행합니다.</p><div class="tablewrap"><table><thead><tr><th></th><th>SESSION</th><th>GPS</th><th>LABEL</th></tr></thead><tbody id="gps-record-rows"></tbody></table></div><div class="row" style="margin-top:8px"><input id="gps-route-id" placeholder="route_id"><button id="gps-route-build" class="primary">정규화 Route 생성</button></div></div>
 <div class="panel span5"><h2>ROUTE + GPS AI MODEL</h2><p class="sectionnote">AUTO_GPS 모델은 학습에 사용한 normalized Route와 ID가 일치해야 합니다.</p><div class="row"><select id="gps-route"></select><select id="gps-model"></select><button id="gps-select">선택 저장</button></div><pre id="gps-status" style="margin-top:8px">-</pre></div>
</div></section>
<section id="view-local" class="view"><div class="grid">
 <div class="panel span6"><h2>LOCAL MAP</h2><div class="row"><input id="map-name" placeholder="새 지도 이름"><button id="map-create">지도 생성</button></div><div class="row" style="margin-top:8px"><select id="map-select"></select><select id="dest-select"></select><button id="local-select">선택 저장</button></div><div class="actions" style="margin-top:8px"><button id="map-start">Mapping 시작</button><button id="map-refine">선택 지도 정밀화</button><button id="map-stop">저장 / 종료</button></div></div>
 <div class="panel span6"><h2>DESTINATION</h2><p class="sectionnote">Mapping 또는 LOCAL localization 중 현재 pose를 named destination으로 저장합니다.</p><div class="row"><input id="dest-name" placeholder="목적지 이름"><button id="dest-current">현재 위치 저장</button></div><pre id="local-status" style="margin-top:8px">-</pre></div>
</div></section>
<section id="view-hardware" class="view"><div class="grid">
 <div class="panel span12"><h2>SENSOR HEALTH</h2><div id="sensor-grid" class="sensorgrid"></div></div>
 <div class="panel span7"><h2>CAMERA / LiDAR</h2><img class="camera" src="/stream.mjpg"><div class="split" style="margin-top:8px"><pre id="lidar-status">-</pre><pre id="camera-status">-</pre></div></div>
 <div class="panel span5"><h2>STEERING / IMU MAINTENANCE</h2><div class="actions"><button id="steer-center">Steering Center</button><button id="steer-stop">Steering Stop</button><button id="imu-calibrate">IMU Calibrate</button><button id="imu-zero">IMU Zero Heading</button><button id="camera-reload">Camera Calibration Reload</button></div><pre id="steer-status" style="margin-top:8px">-</pre><pre id="imu-status" style="margin-top:8px">-</pre><pre id="throttle-status" style="margin-top:8px">-</pre></div>
 </div></section>
<section id="view-system" class="view"><div class="grid">
 <div class="panel span6"><h2>NTRIP / NETWORK</h2><p class="sectionnote">운영 화면에서는 비밀번호/credential을 다시 노출하지 않고 상태와 연결 종료/검색만 제공합니다. 설정 파일은 기존 backend와 호환됩니다.</p><div class="actions"><button id="ntrip-stop">NTRIP Stop</button><button id="wifi-scan">Wi-Fi Scan</button></div><pre id="ntrip-status" style="margin-top:8px">-</pre><pre id="network-status" style="margin-top:8px">-</pre></div>
 <div class="panel span6"><h2>SYSTEM</h2><p class="sectionnote">재부팅/종료는 차량이 정지한 상태에서만 사용하세요.</p><div class="actions"><button id="reboot" class="warnbtn">REBOOT</button><button id="poweroff" class="danger">POWER OFF</button></div><pre id="system-status" style="margin-top:8px">-</pre></div>
</div></section>
<section id="view-debug" class="view"><div class="grid"><div class="panel span6"><h2>V2 RAW STATUS</h2><pre id="raw-v2">-</pre></div><div class="panel span6"><h2>LEGACY BACKEND RAW STATUS</h2><p class="sectionnote">백엔드 호환성 확인용입니다. 예전 AUTO_ROUTE/AUTO_HYBRID 조작 UI는 제거했습니다.</p><pre id="raw-legacy">-</pre></div></div></section>
<div class="footer-note">Legacy hardware APIs are retained for compatibility · Deprecated AUTO_ROUTE/AUTO_HYBRID are not operator modes</div>
</main>
<script>
const $=id=>document.getElementById(id);let S=null,G=null,R=null,D=null,H=null,L=null,I=null,T=null,C=null,N=null,LS=null;const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const r=await fetch(path,{cache:'no-store',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}function post(path,body={},headers={}){return api(path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)})}function pretty(v){return JSON.stringify(v,null,2)}function bytes(v){if(!Number.isFinite(v))return '-';if(v>1073741824)return(v/1073741824).toFixed(1)+' GB';if(v>1048576)return(v/1048576).toFixed(1)+' MB';return Math.round(v/1024)+' KB'}
function showView(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));location.hash=name}document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));showView((location.hash||'#drive').slice(1));
function fill(el,items,key,label,selected){el.innerHTML='';for(const it of items||[]){const o=document.createElement('option');o.value=it[key];o.textContent=label(it);if(String(o.value)===String(selected||''))o.selected=true;el.appendChild(o)}}
function healthName(obj){if(obj?.is_valid===true||obj?.connected===true||obj?.online===true)return['OK','good'];if(obj?.is_valid===false||obj?.connected===false||obj?.online===false)return['CHECK','bad'];return['UNKNOWN','warn']}
function render(){if(!S)return;const mode=S.state?.canonical_mode||S.state?.mode||'-';$('head-mode').textContent=`MODE ${mode}`;$('st-mode').textContent=mode;$('st-record').textContent=S.recording?.active?'ACTIVE':'OFF';$('st-gps').textContent=G?.manual_preflight?.ready?'READY':(G?.selected?.route_id?'CONFIGURED':'NOT READY');$('st-local').textContent=S.local?.configured?'READY':'NOT READY';$('st-ai').textContent=S.ai?.selected_model_id||'-';const safety=S.safety||S.navigation?.safety||{};$('st-safety').textContent=safety.stop_reason||'NORMAL';$('st-safety').className=safety.stop_reason?'bad':'good';document.querySelectorAll('[data-card]').forEach(x=>x.classList.toggle('active',x.dataset.card===mode));$('drive-note').textContent=pretty({state:S.state,auto:S.auto?.selector,gps:G?.selected,local:S.local?.selected,ai:S.ai?.selected_model_id});
 const models=(S.ai?.models||[]).filter(x=>(x.policy_type||'AUTO_AI')==='AUTO_AI');fill($('ai-model'),models,'model_id',x=>`${x.model_id} · ${x.validation_stage}`,S.ai?.selected_model_id);$('ai-model-status').textContent=pretty(S.ai);$('env-tags').value=(S.auto?.config?.environment_tags||[]).join(',');$('auto-selector').textContent=pretty(S.auto?.selector);
 const maps=S.local?.maps||[];fill($('map-select'),maps,'map_id',x=>`${x.name} · ${x.map_id}`,S.local?.selected?.map_id);renderDestinations();$('local-status').textContent=pretty({selected:S.local?.selected,mapping:S.local?.mapping,controller:S.local?.controller,current_pose:S.local?.current_pose});$('raw-v2').textContent=pretty(S);
 if(G){fill($('gps-route'),G.routes||[],'route_id',x=>`${x.route_id} · ${x.point_count} pts`,G.selected?.route_id);fill($('gps-model'),G.models||[],'model_id',x=>`${x.model_id} · ${x.validation_stage}`,G.selected?.model_id);$('gps-status').textContent=pretty(G)}
 if(D){$('dataset-status').textContent=pretty(D)}if(R){renderRecordings()}if(H){const keys=['camera','gps','imu','lidar','steering','arduino'];$('sensor-grid').innerHTML=keys.map(k=>{const v=H[k]||{};const [txt,cls]=healthName(v);return`<div class="sensor"><span>${k.toUpperCase()}</span><strong class="${cls}">${txt}</strong><small class="muted">${esc(v.error_code||'')}</small></div>`}).join('')}
 if(L)$('lidar-status').textContent=pretty({connected:L.connected,rotation_hz:L.rotation_hz,point_count:L.point_count,error:L.error});if(C)$('camera-status').textContent=pretty(C);if(I)$('imu-status').textContent=pretty(I);if(T)$('throttle-status').textContent=pretty(T);if(LS){$('steer-status').textContent=pretty(LS.navigation||LS.devices||LS);$('system-status').textContent=pretty(LS.system||LS);$('network-status').textContent=pretty(LS.network||{}) ;$('raw-legacy').textContent=pretty(LS)}if(N)$('ntrip-status').textContent=pretty(N)}
function renderDestinations(){if(!S)return;const map=(S.local?.maps||[]).find(x=>x.map_id===$('map-select').value)||(S.local?.maps||[]).find(x=>x.map_id===S.local?.selected?.map_id);fill($('dest-select'),map?.destinations||[],'destination_id',x=>x.name,S.local?.selected?.destination_id)}$('map-select').onchange=renderDestinations;
function renderRecordings(){const rows=R?.sessions||[];$('record-rows').innerHTML=rows.map(x=>`<tr><td><input class="rec-ai" type="checkbox" value="${esc(x.session)}" ${x.active?'disabled':''}></td><td>${esc(x.session)}</td><td>${esc(x.label||'')}</td><td>${bytes(x.size_bytes)}</td><td>${x.has_route?'YES':'NO'}</td></tr>`).join('');$('gps-record-rows').innerHTML=rows.map(x=>`<tr><td><input class="rec-gps" type="checkbox" value="${esc(x.session)}" ${(!x.has_route||x.active)?'disabled':''}></td><td>${esc(x.session)}</td><td>${x.has_route?'YES':'NO'}</td><td>${esc(x.label||'')}</td></tr>`).join('')}
async function refresh(){const calls=[api('/api/v2/status'),api('/api/v2/gps-ai'),api('/api/recordings'),api('/api/v2/ai/datasets'),api('/api/sensors/health'),api('/api/lidar'),api('/api/imu'),api('/api/throttle/calibration'),api('/api/camera/calibration'),api('/api/ntrip'),api('/api/status'),api('/api/steering')];const out=await Promise.allSettled(calls);[S,G,R,D,H,L,I,T,C,N,LS]=out.slice(0,11).map(x=>x.status==='fulfilled'?x.value:null);if(out[11].status==='fulfilled'){LS={...(LS||{}),steering:out[11].value}}render()}
async function action(fn){try{await fn();await refresh()}catch(e){alert(e.message)}}document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>action(()=>post('/api/v2/mode',{mode:b.dataset.mode,record_gps:$('record-gps').checked})));$('disarm').onclick=()=>action(()=>post('/api/v2/mode',{mode:'DISARMED'}));$('estop').onclick=()=>{if(confirm('EMERGENCY STOP?'))action(()=>post('/api/safety/emergency-stop',{}))};$('reset-safety').onclick=()=>action(()=>post('/api/safety/reset',{}));$('refresh').onclick=refresh;
$('dataset-build').onclick=()=>action(()=>post('/api/v2/ai/datasets/build',{sessions:[...document.querySelectorAll('.rec-ai:checked')].map(x=>x.value),dataset_id:$('dataset-id').value||null}));$('ai-select').onclick=()=>action(()=>post('/api/v2/ai/select',{model_id:$('ai-model').value}));$('ai-stage-set').onclick=()=>{const stage=$('ai-stage').value;if(confirm(`Lifecycle을 ${stage}로 변경합니까? 실제 검증 증거와 일치해야 합니다.`))action(()=>post('/api/v2/ai/lifecycle',{model_id:$('ai-model').value,stage,confirm:stage}))};$('env-save').onclick=()=>action(()=>post('/api/v2/auto/environment',{tags:$('env-tags').value}));
$('gps-route-build').onclick=()=>action(()=>post('/api/v2/gps-ai/routes/build',{route_id:$('gps-route-id').value,sessions:[...document.querySelectorAll('.rec-gps:checked')].map(x=>x.value)}));$('gps-select').onclick=()=>action(()=>post('/api/v2/gps-ai/select',{route_id:$('gps-route').value,model_id:$('gps-model').value}));
$('map-create').onclick=()=>action(()=>post('/api/v2/maps/create',{name:$('map-name').value}));$('local-select').onclick=()=>action(()=>post('/api/v2/maps/select',{map_id:$('map-select').value,destination_id:$('dest-select').value}));$('map-start').onclick=()=>action(()=>post('/api/v2/maps/mapping/start',{map_id:$('map-select').value||null,name:$('map-name').value,refine:false}));$('map-refine').onclick=()=>action(()=>post('/api/v2/maps/mapping/start',{map_id:$('map-select').value,refine:true}));$('map-stop').onclick=()=>action(()=>post('/api/v2/maps/mapping/stop',{save:true}));$('dest-current').onclick=()=>action(()=>post('/api/v2/maps/destination',{map_id:$('map-select').value,name:$('dest-name').value,use_current_pose:true}));
$('steer-center').onclick=()=>action(()=>post('/api/steering/center',{}));$('steer-stop').onclick=()=>action(()=>post('/api/steering/stop',{}));$('imu-calibrate').onclick=()=>action(()=>post('/api/imu/calibrate',{}));$('imu-zero').onclick=()=>action(()=>post('/api/imu/zero-heading',{}));$('camera-reload').onclick=()=>action(()=>post('/api/camera/calibration/reload',{}));$('ntrip-stop').onclick=()=>action(()=>post('/api/ntrip/stop',{}));$('wifi-scan').onclick=()=>action(async()=>{$('network-status').textContent=pretty(await api('/api/network/wifi/scan'))});$('reboot').onclick=()=>{if(confirm('Raspberry Pi를 재부팅합니까?'))action(()=>post('/api/system/reboot',{}, {'X-GNSS-Confirm':'reboot'}))};$('poweroff').onclick=()=>{if(confirm('Raspberry Pi를 종료합니까?'))action(()=>post('/api/system/poweroff',{}, {'X-GNSS-Confirm':'poweroff'}))};
refresh().catch(e=>alert(e.message));setInterval(()=>refresh().catch(()=>{}),1800);
</script>
</body></html>'''.encode('utf-8')


__all__ = ["UNIFIED_DASHBOARD_HTML"]
