'''Guided user-facing setup and data management enhancements for /v2.'''

USER_MANAGEMENT_HMI = r'''
<style id="user-management-hmi-style">
.setup-overview{margin:0 0 14px;padding:14px 16px;border:1px solid rgba(255,255,255,.09);border-radius:6px;background:#111414}
.setup-overview-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.setup-overview-head strong{font-size:13px}.setup-overview-head small{color:var(--muted);font-size:9px}
.setup-overview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:rgba(255,255,255,.07)}
.setup-overview-card{min-width:0;padding:10px 12px;background:#151818}.setup-overview-card span{display:block;color:#7f8783;font-size:9px}.setup-overview-card b{display:block;margin-top:5px;font-size:11px;font-weight:650}.setup-overview-card small{display:block;margin-top:4px;color:#858c88;font-size:8px;line-height:1.4}
.setup-overview-card.good b{color:var(--ok)}.setup-overview-card.warn b{color:var(--warn)}.setup-overview-card.bad b{color:var(--bad)}
.setup-inline{margin-top:9px;padding:9px 10px;border-left:3px solid rgba(255,255,255,.16);background:#121515;color:#9ba29e;font-size:9px;line-height:1.5}.setup-inline.good{border-left-color:var(--ok)}.setup-inline.warn{border-left-color:var(--warn)}.setup-inline.bad{border-left-color:var(--bad)}
.setup-action-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:9px}.setup-action-row button{min-height:34px}
.setup-help{margin:7px 0 0;color:#7f8783;font-size:9px;line-height:1.45}
.setup-field-state{min-height:18px;margin-top:5px;color:#858c88;font-size:9px}.setup-field-state.good{color:var(--ok)}.setup-field-state.warn{color:var(--warn)}.setup-field-state.bad{color:var(--bad)}
.setup-lifecycle{margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,.07)}.setup-lifecycle-line{display:flex;align-items:center;justify-content:space-between;gap:10px}.setup-lifecycle-line span{color:#858c88;font-size:9px}.setup-lifecycle-line b{font-size:10px}.setup-lifecycle button{margin-top:8px;width:100%}
.setup-chip-row{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.setup-chip{min-height:26px;padding:4px 8px;border:1px solid rgba(255,255,255,.09);border-radius:4px;background:#171a1a;color:#b8bdb9;font-size:9px;font-weight:550}.setup-chip:hover{background:#1b1e1e}
#ai-stage,#ai-stage-set{display:none!important}#map-create{display:none!important}#record-replay-load{display:none!important}
.connection-box .setup-network-list{width:100%;min-height:38px;margin-bottom:8px}.connection-box .setup-connection-status{margin-top:8px;font-size:9px;color:#858c88;line-height:1.45}
@media(max-width:900px){.setup-overview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.setup-overview-grid{grid-template-columns:1fr}.setup-lifecycle-line{align-items:flex-start;flex-direction:column}}
</style>
<script>
(function(){
 const q=id=>document.getElementById(id);
 const modeName=mode=>({DISARMED:'정지',MANUAL:'수동 운전',MANUAL_ASSIST:'수동 전환',RECORD:'주행 기록',AUTO_AI:'AI 자율주행',AUTO_GPS:'GPS 자율주행',AUTO_LOCAL:'지도 자율주행',AUTO:'자동 자율주행',EMERGENCY_STOP:'긴급 정지',FAULT:'점검 필요'}[mode]||mode||'확인 중');
 const stageOrder=['TRAINED','OFFLINE_VALIDATED','CLOSED_AREA_VALIDATED','AUTO_ALLOWED'];
 const stageName=stage=>({TRAINED:'학습 완료',OFFLINE_VALIDATED:'기본 검증 완료',CLOSED_AREA_VALIDATED:'시험 주행 완료',AUTO_ALLOWED:'자동 주행 사용 가능'}[stage]||'확인 필요');
 const nextStage=stage=>{const i=stageOrder.indexOf(stage);return i>=0&&i<stageOrder.length-1?stageOrder[i+1]:null};
 const explainError=raw=>{const s=String(raw||'');if(/RECORDING_IN_USE_BY_DATASET/.test(s))return '이 기록은 학습 데이터에서 사용 중이라 삭제할 수 없습니다.';if(/requires at least two|at least two GPS|normalization requires/.test(s))return 'GPS 경로는 같은 코스를 기록한 GPS 주행 기록이 최소 2개 필요합니다.';if(/Dataset already exists/i.test(s))return '같은 이름의 학습 데이터가 이미 있습니다. 다른 이름을 사용해 주세요.';if(/GPS route already exists/i.test(s))return '같은 이름의 GPS 경로가 이미 있습니다. 다른 이름을 사용해 주세요.';if(/Map already exists/i.test(s))return '같은 이름의 지도가 이미 있습니다. 다른 이름을 사용해 주세요.';if(/too few valid scans/i.test(s))return '유효한 거리 센서 데이터가 부족합니다. 조금 더 이동한 뒤 지도를 저장해 주세요.';if(/fresh IMU|IMU global heading/i.test(s))return '자세 센서 상태를 확인한 뒤 다시 시도해 주세요.';if(/connected LiDAR|populated LiDAR/i.test(s))return 'LiDAR 연결과 데이터 수신 상태를 확인해 주세요.';if(/lifecycle|intermediate stage/i.test(s))return '모델 검증 단계를 순서대로 완료해 주세요.';if(/Stop .* before|Mapping is active|autonomous driving/i.test(s))return '현재 진행 중인 주행 또는 지도 작업을 먼저 종료해 주세요.';return typeof friendlyError==='function'?friendlyError(new Error(s)):'요청을 처리하지 못했습니다. 입력 내용과 현재 상태를 확인해 주세요.'};
 function toast(message,kind=''){let el=q('setup-toast');if(!el){el=document.createElement('div');el.id='setup-toast';el.className='setup-inline';const main=document.querySelector('main');main?.insertBefore(el,main.firstChild)}el.className=`setup-inline ${kind}`;el.textContent=message}
 function safeAction(fn,success){return (async()=>{try{await fn();await refresh();if(success)toast(success,'good')}catch(error){console.error(error);toast(explainError(error?.message||error),'bad')}})()}
 function statusClass(ready,checking=false){return checking?'warn':ready?'good':'warn'}
 function overview(){let box=q('setup-overview');if(!box){box=document.createElement('section');box.id='setup-overview';box.className='setup-overview';box.innerHTML='<div class="setup-overview-head"><strong>설정 및 데이터 관리</strong><small>주행 준비 상태를 먼저 확인하고 필요한 항목만 설정하세요.</small></div><div id="setup-overview-grid" class="setup-overview-grid"></div>';document.querySelector('main')?.insertBefore(box,document.querySelector('main')?.firstChild)}const aiReady=!!S?.capabilities?.AUTO_AI?.ready;const gpsReady=!!G?.manual_preflight?.ready;const localChecking=!!S?.local?.preflight?.checking;const localReady=!!S?.local?.preflight_ready;const buildActive=!!D?.build?.active;const mode=S?.state?.canonical_mode||S?.state?.mode;const grid=q('setup-overview-grid');if(!grid)return;const card=(label,value,note,cls)=>`<div class="setup-overview-card ${cls}"><span>${label}</span><b>${value}</b><small>${note}</small></div>`;grid.innerHTML=card('현재 차량',modeName(mode),buildActive?'학습 데이터 생성 작업이 진행 중입니다.':'현재 차량 상태입니다.',mode==='FAULT'||mode==='EMERGENCY_STOP'?'bad':'')+card('AI 자율주행',aiReady?'준비 완료':'준비 필요',aiReady?'선택한 모델로 주행할 수 있습니다.':'모델 선택과 검증 상태를 확인하세요.',statusClass(aiReady))+card('GPS 자율주행',gpsReady?'준비 완료':'준비 필요',gpsReady?'선택한 경로와 모델을 사용할 수 있습니다.':'RTK·경로·모델 조합을 확인하세요.',statusClass(gpsReady))+card('지도 자율주행',localReady?'준비 완료':localChecking?'위치 확인 중':'준비 필요',localReady?'선택한 지도와 목적지를 사용할 수 있습니다.':'지도·목적지·현재 위치를 확인하세요.',statusClass(localReady,localChecking))}
 function selectedAiRecords(){return [...document.querySelectorAll('.rec-ai:checked')].map(x=>x.value)}function selectedGpsRecords(){return [...document.querySelectorAll('.rec-gps:checked')].map(x=>x.value)}
 function ensureDataHelpers(){const build=q('dataset-build');if(build&&!q('dataset-selection-state')){const s=document.createElement('div');s.id='dataset-selection-state';s.className='setup-field-state';build.parentElement?.insertAdjacentElement('afterend',s)}const ds=q('dataset-status');if(ds&&!q('dataset-build-summary')){const s=document.createElement('div');s.id='dataset-build-summary';s.className='setup-inline';ds.insertAdjacentElement('afterend',s)}const model=q('ai-model');if(model&&!q('setup-lifecycle')){const panel=model.closest('.panel');const box=document.createElement('div');box.id='setup-lifecycle';box.className='setup-lifecycle';box.innerHTML='<div class="setup-lifecycle-line"><span>현재 모델 검증 상태</span><b id="setup-lifecycle-current">확인 중</b></div><button id="setup-lifecycle-next" type="button">다음 검증 단계로 변경</button><p class="setup-help">검증을 실제로 완료한 경우에만 다음 단계로 변경하세요. 검증 단계를 건너뛸 수 없습니다.</p>';panel?.appendChild(box);q('setup-lifecycle-next').onclick=promoteModel}const env=q('env-tags');if(env&&!q('env-model-chips')){const chips=document.createElement('div');chips.id='env-model-chips';chips.className='setup-chip-row';env.closest('.panel')?.appendChild(chips)}}
 function syncData(){ensureDataHelpers();const sessions=selectedAiRecords();const active=!!D?.build?.active;const state=q('dataset-selection-state');if(state){state.textContent=active?'학습 데이터를 만드는 중입니다.':sessions.length?`${sessions.length}개 기록 선택됨${sessions.length<3?' · 3개 이상을 권장합니다.':''}`:'학습에 사용할 주행 기록을 선택하세요.';state.className=`setup-field-state ${active?'warn':sessions.length?'good':'warn'}`}const build=q('dataset-build');if(build){build.disabled=active||sessions.length<1;build.textContent=active?'학습 데이터 만드는 중…':'선택한 기록으로 학습 데이터 만들기'}const id=q('dataset-id');if(id){id.disabled=active;id.title='영문/숫자/-/_/. 사용 가능. 비워두면 자동 이름을 사용합니다.'}const sum=q('dataset-build-summary');if(sum){const b=D?.build||{};if(b.active){sum.className='setup-inline warn';sum.textContent=`${(b.sessions||[]).length}개 기록으로 학습 데이터를 만드는 중입니다.`}else if(b.error){sum.className='setup-inline bad';sum.textContent=explainError(b.error)}else if(b.result){const accepted=Number(b.result.accepted_samples||0);const rejected=Number(b.result.rejected_samples||0);sum.className='setup-inline good';sum.textContent=`${b.result.dataset_id||'학습 데이터'} 생성 완료 · 사용 ${accepted}개 / 제외 ${rejected}개 샘플`}else{sum.className='setup-inline';sum.textContent='기록을 선택하면 카메라·LiDAR·조향·스로틀 시점을 맞춰 학습 데이터를 만듭니다.'}}const models=(S?.ai?.models||[]).filter(x=>(x.policy_type||'AUTO_AI')==='AUTO_AI');const model=models.find(x=>x.model_id===q('ai-model')?.value)||models.find(x=>x.model_id===S?.ai?.selected_model_id);const current=q('setup-lifecycle-current');const next=q('setup-lifecycle-next');if(current)current.textContent=model?stageName(model.validation_stage):'모델을 선택하세요.';if(next){const ns=model?nextStage(model.validation_stage):null;next.disabled=!model||!ns||!!S?.ai?.controller?.active;next.textContent=!model?'모델을 먼저 선택하세요':ns?`${stageName(ns)}로 변경`:'검증 단계 완료'}const chips=q('env-model-chips');if(chips){const tags=model?.environments||[];chips.innerHTML=tags.length?tags.map(tag=>`<button class="setup-chip" type="button" data-env-chip="${String(tag).replace(/"/g,'&quot;')}">${tag}</button>`).join(''):'<span class="setup-help">선택한 모델에 등록된 운행 환경이 없습니다.</span>';chips.querySelectorAll('[data-env-chip]').forEach(btn=>btn.onclick=()=>{const e=q('env-tags');const values=new Set(String(e.value||'').split(',').map(x=>x.trim()).filter(Boolean));values.add(btn.dataset.envChip);e.value=[...values].join(', ')})}const aiSelect=q('ai-select');if(aiSelect)aiSelect.disabled=!q('ai-model')?.value||!!S?.ai?.controller?.active}
 async function promoteModel(){const select=q('ai-model');const models=(S?.ai?.models||[]).filter(x=>(x.policy_type||'AUTO_AI')==='AUTO_AI');const model=models.find(x=>x.model_id===select?.value);if(!model)return toast('변경할 모델을 선택해 주세요.','warn');const target=nextStage(model.validation_stage);if(!target)return toast('이미 가장 높은 검증 단계입니다.','good');if(!confirm(`${model.model_id} 모델을 “${stageName(target)}” 상태로 변경할까요?\n\n실제 검증을 완료한 경우에만 진행하세요.`))return;await safeAction(()=>post('/api/v2/ai/lifecycle',{model_id:model.model_id,stage:target,confirm:target}),`${stageName(target)} 상태로 변경했습니다.`)}
 function ensureGpsHelpers(){const btn=q('gps-route-build');if(btn&&!q('gps-selection-state')){const s=document.createElement('div');s.id='gps-selection-state';s.className='setup-field-state';btn.parentElement?.insertAdjacentElement('afterend',s)}const select=q('gps-route');if(select&&!q('gps-pair-state')){const s=document.createElement('div');s.id='gps-pair-state';s.className='setup-inline';select.closest('.panel')?.appendChild(s)}}
 function syncGps(){ensureGpsHelpers();const records=selectedGpsRecords();const id=String(q('gps-route-id')?.value||'').trim();const build=q('gps-route-build');const state=q('gps-selection-state');if(state){state.textContent=records.length<2?`${records.length}개 선택됨 · 같은 코스의 GPS 기록을 최소 2개 선택하세요.`:`${records.length}개 기록 선택됨 · 경로 이름을 확인하고 생성하세요.`;state.className=`setup-field-state ${records.length>=2?'good':'warn'}`}if(build)build.disabled=records.length<2||!id;const routeId=q('gps-route')?.value||'';const all=G?.models||[];const compatible=all.filter(m=>String(m.route_id||'')===routeId);const modelSelect=q('gps-model');if(modelSelect){const before=modelSelect.value;modelSelect.innerHTML='';compatible.forEach(m=>{const o=document.createElement('option');o.value=m.model_id;o.textContent=`${m.model_id} · ${stageName(m.validation_stage)}`;modelSelect.appendChild(o)});if([...modelSelect.options].some(o=>o.value===before))modelSelect.value=before;else if(G?.selected?.route_id===routeId&&[...modelSelect.options].some(o=>o.value===G?.selected?.model_id))modelSelect.value=G.selected.model_id}const selected=compatible.find(m=>m.model_id===modelSelect?.value);const usable=!!selected&&['CLOSED_AREA_VALIDATED','AUTO_ALLOWED'].includes(selected.validation_stage);const selectBtn=q('gps-select');if(selectBtn)selectBtn.disabled=!routeId||!selected||!usable;const pair=q('gps-pair-state');if(pair){if(!routeId){pair.className='setup-inline warn';pair.textContent='먼저 사용할 GPS 경로를 선택하세요.'}else if(!compatible.length){pair.className='setup-inline warn';pair.textContent='이 경로에 연결된 GPS 주행 모델이 없습니다.'}else if(!usable){pair.className='setup-inline warn';pair.textContent='선택한 모델은 시험 주행 검증이 아직 완료되지 않았습니다.'}else{pair.className='setup-inline good';pair.textContent=`${routeId} 경로와 ${selected.model_id} 모델 조합을 사용할 수 있습니다.`}}}
 function ensureLocalHelpers(){const start=q('map-start');if(start)start.textContent='새 지도 기록 시작'}
 function syncLocal(){ensureLocalHelpers();const mapping=!!S?.local?.mapping?.active;const localActive=!!S?.local?.controller?.active;const maps=S?.local?.maps||[];const map=maps.find(m=>m.map_id===q('map-select')?.value);const name=String(q('map-name')?.value||'').trim();const mappingId=S?.local?.mapping?.map_id||'';if(mapping&&mappingId&&q('map-select')&&[...q('map-select').options].some(o=>o.value===mappingId)){q('map-select').value=mappingId;if(typeof renderDestinations==='function')renderDestinations()}const activeMap=maps.find(m=>m.map_id===q('map-select')?.value)||map;const activeHasAsset=!!activeMap?.map_file;const start=q('map-start');if(start){start.disabled=mapping||localActive||!name;start.textContent=mapping&&!S?.local?.mapping?.refine?'지도 기록 중…':'새 지도 기록 시작'}const refine=q('map-refine');if(refine){refine.disabled=mapping||localActive||!activeMap||!activeHasAsset;refine.textContent=mapping&&S?.local?.mapping?.refine?'지도 업데이트 중…':'선택한 지도 업데이트'}const stop=q('map-stop');if(stop)stop.disabled=!mapping;const dest=q('dest-current');if(dest)dest.disabled=!activeMap||!String(q('dest-name')?.value||'').trim()||!(S?.local?.current_pose||S?.local?.mapping?.slam?.pose);const localSelect=q('local-select');if(localSelect)localSelect.disabled=!q('map-select')?.value||!q('dest-select')?.value||mapping||localActive}
 function ensureConnectionHelpers(){const ssid=q('wifi-ssid');if(ssid&&!q('wifi-network-select-user')){const select=document.createElement('select');select.id='wifi-network-select-user';select.className='setup-network-list';select.innerHTML='<option value="">주변 Wi-Fi 검색 후 선택</option>';const scan=document.createElement('button');scan.id='wifi-scan-user';scan.type='button';scan.textContent='주변 Wi-Fi 찾기';ssid.parentElement?.insertBefore(select,ssid);ssid.parentElement?.insertBefore(scan,ssid);select.onchange=()=>{if(select.value){ssid.value=select.value;const option=select.options[select.selectedIndex];q('wifi-security').value=option.dataset.open==='true'?'open':'wpa-psk'}};scan.onclick=scanWifi}const ntrip=q('ntrip-config-save');if(ntrip&&!q('ntrip-enabled-user')){const label=document.createElement('label');label.className='setup-help';label.innerHTML='<input id="ntrip-enabled-user" type="checkbox" checked> 저장 후 RTK 보정 연결 사용';ntrip.parentElement?.insertBefore(label,ntrip)}}
 async function scanWifi(){try{const result=await api('/api/network/wifi/scan');const networks=Array.isArray(result)?result:(result?.networks||[]);const select=q('wifi-network-select-user');if(select)select.innerHTML='<option value="">Wi-Fi 선택</option>'+networks.filter(n=>n?.ssid).map(n=>`<option value="${String(n.ssid).replace(/"/g,'&quot;')}" data-open="${String(n.security||'').toUpperCase()==='OPEN'||!n.security}">${n.ssid}${n.signal!=null?` · ${n.signal}%`:''}</option>`).join('');toast(networks.length?`${networks.length}개의 Wi-Fi를 찾았습니다.`:'주변 Wi-Fi를 찾지 못했습니다.',networks.length?'good':'warn')}catch(error){toast(explainError(error?.message||error),'bad')}}
 function syncConnections(){ensureConnectionHelpers();const n=N||{};const cfg=n.config||n;const fields={'ntrip-host':cfg.host,'ntrip-port':cfg.port,'ntrip-mountpoint':cfg.mountpoint,'ntrip-username':cfg.username,'wifi-ssid':LS?.network?.ssid||LS?.network?.wifi_ssid};Object.entries(fields).forEach(([id,value])=>{const el=q(id);if(el&&document.activeElement!==el&&!el.value&&value!=null)el.value=String(value)});const enabled=q('ntrip-enabled-user');if(enabled&&typeof cfg.enabled==='boolean')enabled.checked=cfg.enabled}
 function syncMaintenance(){const mode=S?.state?.canonical_mode||S?.state?.mode;const autonomous=['AUTO_AI','AUTO_GPS','AUTO_LOCAL','AUTO'].includes(mode);const mapping=!!S?.local?.mapping?.active;['steer-center','imu-calibrate','imu-zero','camera-reload'].forEach(id=>{const el=q(id);if(el)el.disabled=autonomous||mapping});const stop=q('steer-stop');if(stop)stop.disabled=autonomous}
 function syncRecordManager(){const select=q('record-manage-session'),del=q('record-delete');if(!select||!del)return;const session=select.value;const datasetRefs=(D?.datasets||[]).filter(d=>(d.sessions||[]).includes(session)).map(d=>d.dataset_id);const routeRefs=(G?.routes||[]).filter(r=>(r.source_sessions||[]).includes(session)).map(r=>r.route_id);del.disabled=!session||datasetRefs.length>0;let note=q('record-dependency-note');if(!note){note=document.createElement('div');note.id='record-dependency-note';note.className='setup-inline';del.closest('.panel')?.appendChild(note)}if(!session){note.className='setup-inline';note.textContent='기록을 선택하면 사용 중인 데이터 관계를 확인합니다.'}else if(datasetRefs.length){note.className='setup-inline warn';note.textContent=`학습 데이터 ${datasetRefs.join(', ')}에서 원본 영상을 사용 중이므로 삭제할 수 없습니다.`}else if(routeRefs.length){note.className='setup-inline warn';note.textContent=`GPS 경로 ${routeRefs.join(', ')} 생성에 사용한 원본 기록입니다. 삭제해도 현재 경로는 유지되지만 재검토용 원본은 사라집니다.`}else{note.className='setup-inline good';note.textContent='다른 학습 데이터에서 사용하지 않는 기록입니다.'}}
 function syncAll(){overview();syncData();syncGps();syncLocal();syncConnections();syncMaintenance();syncRecordManager()}
 const oldRender=render;render=function(){const aiChecked=new Set([...document.querySelectorAll('.rec-ai:checked')].map(x=>x.value));const gpsChecked=new Set([...document.querySelectorAll('.rec-gps:checked')].map(x=>x.value));const pending={};['ai-model','gps-route','gps-model','map-select','dest-select'].forEach(id=>{const el=q(id);if(el)pending[id]=el.value});const envBefore=q('env-tags')?.value||'';const envFocused=document.activeElement===q('env-tags');oldRender();document.querySelectorAll('.rec-ai').forEach(x=>{if(aiChecked.has(x.value)&&!x.disabled)x.checked=true});document.querySelectorAll('.rec-gps').forEach(x=>{if(gpsChecked.has(x.value)&&!x.disabled)x.checked=true});for(const id of ['ai-model','gps-route','gps-model','map-select']){const el=q(id),value=pending[id];if(el&&value&&[...el.options].some(o=>o.value===value))el.value=value}if(pending['map-select']&&typeof renderDestinations==='function')renderDestinations();const dest=q('dest-select');if(dest&&pending['dest-select']&&[...dest.options].some(o=>o.value===pending['dest-select']))dest.value=pending['dest-select'];if(envFocused&&q('env-tags'))q('env-tags').value=envBefore;syncAll()};
 document.addEventListener('change',event=>{if(event.target.matches('.rec-ai,.rec-gps,#ai-model,#gps-route,#gps-model,#map-select,#dest-select,#record-manage-session'))setTimeout(syncAll,0)});document.addEventListener('input',event=>{if(event.target.matches('#dataset-id,#gps-route-id,#map-name,#dest-name,#env-tags'))syncAll()});
 const datasetBuild=q('dataset-build');if(datasetBuild)datasetBuild.onclick=()=>{const sessions=selectedAiRecords();if(!sessions.length)return toast('학습에 사용할 주행 기록을 선택해 주세요.','warn');return safeAction(()=>post('/api/v2/ai/datasets/build',{sessions,dataset_id:String(q('dataset-id')?.value||'').trim()||null}),'학습 데이터 생성을 시작했습니다.')};
 const gpsBuild=q('gps-route-build');if(gpsBuild)gpsBuild.onclick=()=>{const sessions=selectedGpsRecords();const routeId=String(q('gps-route-id')?.value||'').trim();if(sessions.length<2)return toast('GPS 기록을 최소 2개 선택해 주세요.','warn');if(!routeId)return toast('GPS 경로 이름을 입력해 주세요.','warn');return safeAction(()=>post('/api/v2/gps-ai/routes/build',{route_id:routeId,sessions}),'GPS 경로를 만들었습니다.')};
 const gpsSelect=q('gps-select');if(gpsSelect)gpsSelect.onclick=()=>safeAction(()=>post('/api/v2/gps-ai/select',{route_id:q('gps-route').value,model_id:q('gps-model').value}),'GPS 경로와 주행 모델을 선택했습니다.');
 const mapStart=q('map-start');if(mapStart)mapStart.onclick=()=>{const name=String(q('map-name')?.value||'').trim();if(!name)return toast('새 지도 이름을 입력해 주세요.','warn');return safeAction(()=>post('/api/v2/maps/mapping/start',{map_id:null,name,refine:false}),'새 지도 기록을 시작했습니다.')};
 const mapRefine=q('map-refine');if(mapRefine)mapRefine.onclick=()=>safeAction(()=>post('/api/v2/maps/mapping/start',{map_id:q('map-select').value,refine:true}),'선택한 지도 업데이트를 시작했습니다.');const mapStop=q('map-stop');if(mapStop)mapStop.onclick=()=>safeAction(()=>post('/api/v2/maps/mapping/stop',{save:true}),'지도를 저장했습니다.');const localSelect=q('local-select');if(localSelect)localSelect.onclick=()=>safeAction(()=>post('/api/v2/maps/select',{map_id:q('map-select').value,destination_id:q('dest-select').value}),'지도와 목적지를 선택했습니다.');const destCurrent=q('dest-current');if(destCurrent)destCurrent.onclick=()=>{const name=String(q('dest-name')?.value||'').trim();if(!name)return toast('목적지 이름을 입력해 주세요.','warn');return safeAction(()=>post('/api/v2/maps/destination',{map_id:q('map-select').value,name,use_current_pose:true}),'현재 위치를 목적지로 저장했습니다.')};
 const envSave=q('env-save');if(envSave)envSave.onclick=()=>safeAction(()=>post('/api/v2/auto/environment',{tags:String(q('env-tags')?.value||'')}),'자동 주행 환경을 저장했습니다.');
 const wifiScan=q('wifi-scan');if(wifiScan)wifiScan.onclick=scanWifi;const wifiConnect=q('wifi-connect');if(wifiConnect)wifiConnect.onclick=()=>{const ssid=String(q('wifi-ssid')?.value||'').trim(),security=q('wifi-security')?.value||'wpa-psk',password=String(q('wifi-password')?.value||'');if(!ssid)return toast('연결할 Wi-Fi를 선택하거나 이름을 입력해 주세요.','warn');if(security!=='open'&&!password)return toast('Wi-Fi 비밀번호를 입력해 주세요.','warn');if(!confirm(`Wi-Fi를 “${ssid}”로 변경할까요?\n\n현재 Wi-Fi로 대시보드에 접속 중이면 연결이 잠시 끊길 수 있습니다.`))return;safeAction(()=>post('/api/network/wifi/connect',{ssid,password,security}),'Wi-Fi 연결 요청을 보냈습니다.')};const wifiDisconnect=q('wifi-disconnect');if(wifiDisconnect)wifiDisconnect.onclick=()=>{if(confirm('Wi-Fi 연결을 끊을까요? 현재 접속이 끊길 수 있습니다.'))safeAction(()=>post('/api/network/wifi/disconnect',{}),'Wi-Fi 연결을 끊었습니다.')};
 const ntripSave=q('ntrip-config-save');if(ntripSave)ntripSave.onclick=()=>{const host=String(q('ntrip-host')?.value||'').trim(),mountpoint=String(q('ntrip-mountpoint')?.value||'').trim();if(!host||!mountpoint)return toast('RTK 서버 주소와 마운트포인트를 입력해 주세요.','warn');safeAction(()=>post('/api/ntrip/config',{host,port:Number(q('ntrip-port')?.value)||2101,mountpoint,username:String(q('ntrip-username')?.value||'').trim(),password:String(q('ntrip-password')?.value||''),enabled:q('ntrip-enabled-user')?.checked!==false,tls:false}),'RTK 연결 정보를 저장했습니다.')};
 const recordSelect=q('record-manage-session');if(recordSelect)recordSelect.addEventListener('change',()=>{const session=recordSelect.value;if(!session)return;safeAction(async()=>{const result=await post('/api/recordings/replay',{session,offset_seconds:0});const slider=q('record-replay-slider');if(slider){slider.max=String(result.duration_seconds||0);slider.value='0'}q('record-replay-offset').textContent='0.0초';const status=q('record-replay-status');if(status)status.innerHTML=`<div class="user-summary-card"><span>주행 기록</span><strong>0.0초 / ${Number(result.duration_seconds||0).toFixed(1)}초</strong><small>슬라이더를 움직여 원하는 시점을 확인할 수 있습니다.</small></div>`},null)});
 const recordDelete=q('record-delete');if(recordDelete)recordDelete.onclick=()=>{const session=q('record-manage-session')?.value;if(!session)return toast('삭제할 기록을 선택해 주세요.','warn');const datasetRefs=(D?.datasets||[]).filter(d=>(d.sessions||[]).includes(session)).map(d=>d.dataset_id);if(datasetRefs.length)return toast(`학습 데이터 ${datasetRefs.join(', ')}에서 사용 중이라 삭제할 수 없습니다.`,'warn');const routeRefs=(G?.routes||[]).filter(r=>(r.source_sessions||[]).includes(session)).map(r=>r.route_id);const warning=routeRefs.length?`\n\n이 기록은 GPS 경로 ${routeRefs.join(', ')} 생성에 사용되었습니다. 현재 경로는 유지되지만 원본 기록은 사라집니다.`:'';if(!confirm(`선택한 주행 기록을 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.${warning}`))return;safeAction(()=>post('/api/recordings/delete',{session}),'주행 기록을 삭제했습니다.')};
 syncAll();
})();
</script>
'''.encode('utf-8')

__all__ = ["USER_MANAGEMENT_HMI"]
