'''User-facing drive mode chooser for the primary dashboard.'''

from operator_mode_status import install_operator_mode_status_patch

install_operator_mode_status_patch()


V2_OPTION_PANEL = r'''
<style>
#autonomy-modal .autonomy-safety-actions,#autonomy-modal .settings-grid{display:none!important}
#autonomy-modal .modal-card{grid-template-rows:auto minmax(0,1fr)!important;width:min(900px,calc(100vw - 24px))!important}
#v2-mode-panel{min-height:0;overflow:auto;padding-right:4px}
#v2-mode-panel .v2-intro{margin:0 0 12px;color:#9ba49c;font-size:10px;line-height:1.55}
.v2-mode-state{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0 0 14px}
.v2-mode-state div{padding:10px 12px;border:1px solid #334036;border-radius:10px;background:#101713}
.v2-mode-state span{display:block;color:#7f8a81;font-size:8px;letter-spacing:.04em}
.v2-mode-state b{display:block;margin-top:4px;color:#e2eae1;font:800 11px ui-monospace,monospace}
.v2-mode-state small{display:block;margin-top:4px;color:#7f8981;font-size:8px;line-height:1.4}
.v2-mode-section{margin-top:14px}.v2-mode-section:first-of-type{margin-top:0}
.v2-mode-section-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 8px;color:#c0c9c1;font-size:10px}.v2-mode-section-head small{color:#7e887f;font-size:8px}
.v2-mode-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.v2-mode-grid.human{grid-template-columns:repeat(2,minmax(0,1fr))}.v2-mode-grid.auto-choice{grid-template-columns:1fr}
.v2-mode-card{min-width:0;padding:12px;border:1px solid #303b32;border-radius:10px;background:#121a14;cursor:pointer;transition:border-color .14s ease,background .14s ease,opacity .14s ease}
.v2-mode-card:hover{border-color:#627461;background:#172119}.v2-mode-card.selected{border-color:#8fb378;background:#1c2b1a;box-shadow:0 0 0 1px #8fb37833 inset}.v2-mode-card.unready{border-color:#554a2e}.v2-mode-card.blocked{opacity:.66}
.v2-card-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.v2-mode-card b{font-size:11px}.v2-mode-card p{min-height:42px;margin:7px 0 6px;color:#979f98;font-size:9px;line-height:1.55}
.v2-mode-badge{display:inline-flex;align-items:center;min-height:20px;padding:2px 7px;border:1px solid #405044;border-radius:999px;color:#a5afa6;background:#151d17;font:800 8px ui-monospace,monospace;white-space:nowrap}
.v2-mode-badge.ready{border-color:#42673d;color:#a9db91;background:#142415}.v2-mode-badge.running{border-color:#4f7652;color:#c6f0bd;background:#19301c}.v2-mode-badge.warn{border-color:#665638;color:#e1c278;background:#2b2518}.v2-mode-badge.bad{border-color:#733844;color:#ff9eaa;background:#31161b}.v2-mode-badge.checking{border-color:#53606a;color:#bdcbd3;background:#182027}
.v2-mode-reason{min-height:28px;margin:0 0 8px;color:#828d83;font-size:8px;line-height:1.45}.v2-mode-card.unready .v2-mode-reason{color:#cfb774}.v2-mode-card.blocked .v2-mode-reason{color:#d8949d}
.v2-mode-card button{width:100%;min-height:38px;border:1px solid #435148;border-radius:8px;background:#1d261f;color:#edf3ed;font:750 10px ui-monospace,monospace;cursor:pointer}.v2-mode-card:hover button,.v2-mode-card.selected button{border-color:#91b279;color:#dff2d1}.v2-mode-card.selected button{background:#263621}
.v2-record-option{display:flex;align-items:center;gap:8px;margin:8px 0;padding:9px;border:1px solid #343f36;border-radius:8px;background:#101712;color:#b7c0b8;font-size:9px;cursor:default}.v2-record-option input{width:17px;height:17px}.v2-record-option strong{font-size:9px;color:#d7e0d8}
.v2-auto-hero{border-color:#475d45;background:#142018}.v2-auto-hero p{min-height:0}
.v2-mode-footer{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:13px}.v2-mode-footer small{color:#7f8980;font-size:9px}.v2-mode-footer a{min-height:34px;padding:7px 10px;border:1px solid #425047;border-radius:8px;background:#1b241d;color:#edf3ed;font:750 9px ui-monospace,monospace;text-decoration:none}
#v2-main-runtime{display:inline-flex;align-items:center;min-height:34px;max-width:260px;padding:6px 10px;border:1px solid #33433a;border-radius:8px;background:#101812;color:#b9c6ba;font:750 8px ui-monospace,monospace;line-height:1.3}
#v2-main-runtime.auto{border-color:#52694e;background:#142018;color:#c7dfbd}
#v2-main-action{min-height:34px;padding:6px 11px;border:1px solid #607d56;border-radius:8px;background:#17331d;color:#aee096;font:800 9px ui-monospace,monospace;letter-spacing:.04em;cursor:pointer;white-space:nowrap}
#v2-main-action:hover:not(:disabled){border-color:#9dcc82;background:#214329}#v2-main-action.running{border-color:#8b3947;background:#35151b;color:#ffadb7}#v2-main-action:disabled{opacity:.48;cursor:not-allowed}
#v2-main-estop,#v2-main-reset{min-height:34px;padding:6px 9px;border-radius:8px;font:800 8px ui-monospace,monospace;cursor:pointer;white-space:nowrap}#v2-main-estop{border:1px solid #873c49;background:#35151b;color:#ffadb7}#v2-main-reset{border:1px solid #7a6740;background:#292317;color:#d8bd82}
#autonomy-open.v2-mode-selected{border-color:#607d56;color:#c8e4b8;background:#18251a}#lidar-drive-button{display:none!important}.lidar-drive{grid-template-rows:auto minmax(80px,1fr)!important}
@media(max-width:720px){.v2-mode-grid,.v2-mode-grid.human{grid-template-columns:1fr 1fr}}@media(max-width:520px){.v2-mode-grid,.v2-mode-grid.human,.v2-mode-state{grid-template-columns:1fr}.v2-mode-card p{min-height:0}.v2-mode-footer{align-items:stretch;flex-direction:column}.v2-mode-footer a{text-align:center}#v2-main-runtime{max-width:none}}
</style>
<script>
(function(){
 const MODES=['MANUAL','RECORD','AUTO_AI','AUTO_GPS','AUTO_LOCAL','AUTO'];
 const MODE_SET=new Set(MODES);
 const MODE_NAME={MANUAL:'수동 운전',RECORD:'주행 기록',AUTO_AI:'AI 자율주행',AUTO_GPS:'GPS 자율주행',AUTO_LOCAL:'지도 자율주행',AUTO:'자동 자율주행',PRETRAINED_ROAD:'차선 추적 자율주행'};
 const SELECTED_KEY='swing.v2.selectedMode';const RECORD_GPS_KEY='swing.v2.recordGps';
 const modal=document.getElementById('autonomy-modal');const card=modal?.querySelector('.modal-card');const openButton=document.getElementById('autonomy-open');if(!modal||!card||!openButton)return;
 const throttleLabel=document.querySelector('.lidar-drive-readout span');if(throttleLabel)throttleLabel.textContent='스로틀';
 const title=document.getElementById('autonomy-title');if(title)title.textContent='주행 모드 선택';
 const intro=card.querySelector('.modal-head p');if(intro)intro.textContent='원하는 주행 방식을 고른 뒤 메인 화면에서 시작하세요.';
 const oldSafety=card.querySelector('.autonomy-safety-actions');const panel=document.createElement('section');panel.id='v2-mode-panel';
 panel.innerHTML=`
  <p class="v2-intro">현재 주행 상태를 확인하고 다음에 사용할 주행 방식을 선택할 수 있습니다.</p>
  <div class="v2-mode-state">
   <div><span>현재 주행</span><b id="v2-runtime-mode">확인 중</b><small id="v2-runtime-reason"></small></div>
   <div><span>선택한 주행</span><b id="v2-selected-mode">선택 안 됨</b><small id="v2-auto-reason">선택 후 메인 화면의 시작 버튼을 눌러주세요.</small></div>
  </div>
  <section class="v2-mode-section"><div class="v2-mode-section-head"><strong>직접 운전</strong><small>직접 운전하거나 주행 데이터를 기록합니다.</small></div><div class="v2-mode-grid human">
   <div class="v2-mode-card" data-v2-card="MANUAL"><div class="v2-card-head"><b>수동 운전</b><span class="v2-mode-badge" data-v2-badge="MANUAL">-</span></div><p>게임패드로 차량을 직접 운전합니다.</p><div class="v2-mode-reason" data-v2-reason="MANUAL">바로 사용할 수 있습니다.</div><button data-v2-select="MANUAL" type="button">수동 운전 선택</button></div>
   <div class="v2-mode-card" data-v2-card="RECORD"><div class="v2-card-head"><b>주행 기록</b><span class="v2-mode-badge" data-v2-badge="RECORD">-</span></div><p>직접 운전하면서 자율주행 학습에 사용할 주행 데이터를 저장합니다.</p><label class="v2-record-option"><input id="v2-record-gps" type="checkbox"><span><strong>GPS 위치도 함께 저장</strong><br>GPS 자율주행용 경로를 만들 때 사용합니다.</span></label><div class="v2-mode-reason" data-v2-reason="RECORD">기록 준비 완료</div><button data-v2-select="RECORD" type="button">주행 기록 선택</button></div>
  </div></section>
  <section class="v2-mode-section"><div class="v2-mode-section-head"><strong>자율주행</strong><small>준비된 방식만 시작할 수 있습니다.</small></div><div class="v2-mode-grid">
   <div class="v2-mode-card" data-v2-card="AUTO_AI"><div class="v2-card-head"><b>AI 자율주행</b><span class="v2-mode-badge" data-v2-badge="AUTO_AI">-</span></div><p>카메라와 차량 센서를 이용해 학습된 방식으로 주행합니다.</p><div class="v2-mode-reason" data-v2-reason="AUTO_AI">준비 상태 확인 중</div><button data-v2-select="AUTO_AI" type="button">AI 자율주행 선택</button></div>
   <div class="v2-mode-card" data-v2-card="AUTO_GPS"><div class="v2-card-head"><b>GPS 자율주행</b><span class="v2-mode-badge" data-v2-badge="AUTO_GPS">-</span></div><p>미리 저장한 GPS 경로를 따라 자율주행합니다.</p><div class="v2-mode-reason" data-v2-reason="AUTO_GPS">준비 상태 확인 중</div><button data-v2-select="AUTO_GPS" type="button">GPS 자율주행 선택</button></div>
   <div class="v2-mode-card" data-v2-card="AUTO_LOCAL"><div class="v2-card-head"><b>지도 자율주행</b><span class="v2-mode-badge" data-v2-badge="AUTO_LOCAL">-</span></div><p>저장한 지도를 이용해 선택한 목적지까지 자율주행합니다.</p><div class="v2-mode-reason" data-v2-reason="AUTO_LOCAL">준비 상태 확인 중</div><button data-v2-select="AUTO_LOCAL" type="button">지도 자율주행 선택</button></div>
  </div></section>
  <section class="v2-mode-section"><div class="v2-mode-section-head"><strong>자동 자율주행</strong><small>현재 준비 상태에 가장 알맞은 방식을 자동으로 사용합니다.</small></div><div class="v2-mode-grid auto-choice">
   <div class="v2-mode-card v2-auto-hero" data-v2-card="AUTO"><div class="v2-card-head"><b>자동 자율주행</b><span class="v2-mode-badge" data-v2-badge="AUTO">-</span></div><p>GPS 주행, 지도 주행, 학습 AI 주행을 우선 확인하고, 모두 준비되지 않으면 설치된 UFLD 차선 추적 주행을 안전 조건에서 사용합니다.</p><div class="v2-mode-reason" data-v2-reason="AUTO">준비 상태 확인 중</div><button data-v2-select="AUTO" type="button">자동 자율주행 선택</button></div>
  </div></section>
  <div class="v2-mode-footer"><small>주행 방식 선택만으로 차량이 움직이지 않습니다.</small><a href="/v2">설정 및 데이터 관리</a></div>`;
 if(oldSafety)card.insertBefore(panel,oldSafety);else card.appendChild(panel);
 const runtimeSummary=document.createElement('span');runtimeSummary.id='v2-main-runtime';runtimeSummary.textContent='주행 상태 확인 중';openButton.insertAdjacentElement('afterend',runtimeSummary);
 const mainAction=document.createElement('button');mainAction.id='v2-main-action';mainAction.type='button';runtimeSummary.insertAdjacentElement('afterend',mainAction);
 const estop=document.createElement('button');estop.id='v2-main-estop';estop.type='button';estop.textContent='긴급 정지';mainAction.insertAdjacentElement('afterend',estop);
 const reset=document.createElement('button');reset.id='v2-main-reset';reset.type='button';reset.textContent='안전 상태 해제';reset.hidden=true;estop.insertAdjacentElement('afterend',reset);
 let state=null;let requestBusy=false;let selectedMode=String(localStorage.getItem(SELECTED_KEY)||'').trim().toUpperCase();if(!MODE_SET.has(selectedMode))selectedMode='';
 const recordGps=document.getElementById('v2-record-gps');recordGps.checked=localStorage.getItem(RECORD_GPS_KEY)==='true';recordGps.addEventListener('click',event=>event.stopPropagation());recordGps.addEventListener('change',()=>{localStorage.setItem(RECORD_GPS_KEY,String(recordGps.checked));renderChooser()});recordGps.closest('label')?.addEventListener('click',event=>event.stopPropagation());
 async function json(path,options={}){const response=await fetch(path,{cache:'no-store',...options});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||data.message||`HTTP ${response.status}`);return data}
 async function post(path,payload){return json(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload||{})})}
 function runtimeMode(){return String(state?.state?.canonical_mode||state?.state?.mode||'').trim().toUpperCase()}function capability(mode){return state?.capabilities?.[mode]||null}function safetyBlocked(){return ['EMERGENCY_STOP','E_STOP','FAULT'].includes(runtimeMode())}function humanDriveActive(){return ['MANUAL','RECORD'].includes(runtimeMode())&&!safetyBlocked()}function autoSelector(){return state?.auto?.selector||{}}function autoStrategy(){return String(autoSelector()?.strategy||'').trim().toUpperCase()}function autoIsRunning(){return !!autoSelector()?.active&&['AUTO_AI','AUTO_GPS','AUTO_LOCAL','PRETRAINED_ROAD'].includes(autoStrategy())}function modeName(mode){return MODE_NAME[mode]||'정지'}
 function friendlyError(error){const raw=String(error?.message||error||'');console.error('Drive mode request failed',raw);if(/PRETRAINED_AUTO|PRETRAINED_ROAD|UFLD|LANE_LOST|NEURAL_INFERENCE_TOO_SLOW/i.test(raw))return '차선 추적 자율주행 준비 상태를 확인해 주세요. 카메라 차선 인식과 UFLD 모델/추론 속도를 확인하세요.';if(/EXTERNAL_DATA|external data|onnx\.data|NOT_SELF_CONTAINED/i.test(raw))return 'AI 모델 파일이 완전하지 않습니다. 차량용 단일 ONNX 모델로 다시 설치해 주세요.';if(/DEPENDENCY_MISSING|onnxruntime|OpenCV|NumPy/i.test(raw))return '차량의 AI 추론 라이브러리 설치 상태를 확인해 주세요.';if(/MODEL_LOAD_FAILED|MANIFEST_INVALID|ONNX_CONTRACT_MISMATCH/i.test(raw))return 'AI 모델을 차량에서 불러오지 못했습니다. 모델 파일과 manifest를 확인해 주세요.';if(/map|destination/i.test(raw))return '지도와 목적지를 먼저 선택해 주세요.';if(/localiz/i.test(raw))return '현재 위치를 확인하지 못했습니다. 차량 위치와 지도를 확인해 주세요.';if(/gps|route|rtk/i.test(raw))return 'GPS 경로 준비 상태를 확인해 주세요.';if(/model|ai/i.test(raw))return '사용할 AI 주행 모델의 준비 상태를 확인해 주세요.';if(/safety|emergency|fault/i.test(raw))return '안전 상태를 먼저 확인해 주세요.';return '요청을 처리하지 못했습니다. 차량 연결과 준비 상태를 확인해 주세요.'}
 function reasonText(reason){const value=String(reason||'').trim();const known={human_control:'직접 운전 중',manual_recording:'주행 기록 중',selected_model_ready:'AI 주행 준비 완료',selected_model_runtime_ready:'AI 주행 준비 완료',ai_model_runtime_ready:'AI 주행 준비 완료',gps_preflight_ready:'GPS 주행 준비 완료',gps_ai_model_runtime_ready:'GPS 주행 준비 완료',local_preflight_ready:'지도 주행 준비 완료',local_preflight_checking:'현재 위치 확인 중',gps_strategy_available:'GPS 주행 사용 가능',local_strategy_available:'지도 주행 사용 가능',ai_strategy_available:'AI 주행 사용 가능',pretrained_road_available:'UFLD 차선 추적 주행 사용 가능',pretrained_road_model_ready:'UFLD 차선 추적 주행 준비 완료',no_strategy_ready:'사용할 수 있는 자율주행 방식이 아직 없습니다.',no_strategy_configured:'사용할 수 있는 자율주행 방식이 아직 없습니다.','select map and destination':'지도와 목적지를 먼저 선택해 주세요.',LOCAL_MAP_AND_DESTINATION_REQUIRED:'지도와 목적지를 먼저 선택해 주세요.',LOCAL_PREFLIGHT_CHECKING:'현재 위치 확인 중',LOCALIZATION_FAILED:'현재 위치를 확인하지 못했습니다.',strategy_available:'자율주행 준비 완료'};if(known[value])return known[value];if(/PRETRAINED|UFLD|LANE/i.test(value))return 'UFLD 차선 추적 주행 준비 상태를 확인해 주세요.';if(/DEPENDENCY_MISSING/i.test(value))return '차량의 AI 추론 라이브러리 설치가 필요합니다.';if(/NOT_SELF_CONTAINED|EXTERNAL_DATA/i.test(value))return '차량용 단일 ONNX 모델을 다시 설치해 주세요.';if(/MANIFEST_INVALID|ARTIFACT_MISSING|MODEL_LOAD_FAILED|ONNX_CONTRACT_MISMATCH/i.test(value))return '설치된 AI 모델 파일을 확인해 주세요.';return value?'준비 상태를 확인해 주세요.':'준비 상태를 확인해 주세요.'}
 function syncLegacyManualArm(){const shouldArm=humanDriveActive();try{if(typeof driveArmed==='undefined'||typeof toggleDriveArmed!=='function')return;if(Boolean(driveArmed)!==shouldArm)toggleDriveArmed()}catch(error){console.error('Manual control sync failed',error)}}
 function modeRunning(mode){const current=runtimeMode();if(mode==='MANUAL')return current==='MANUAL';if(mode==='RECORD')return !!state?.recording?.active&&current==='RECORD';if(mode==='AUTO_AI')return !!state?.ai?.controller?.active||current==='AUTO_AI';if(mode==='AUTO_GPS')return !!state?.gps_ai?.controller?.active||current==='AUTO_GPS';if(mode==='AUTO_LOCAL')return !!state?.local?.controller?.active||current==='AUTO_LOCAL';if(mode==='AUTO')return autoIsRunning();return false}
 function isSelectedRunning(){return modeRunning(selectedMode)}function modeStartLabel(mode){if(mode==='RECORD')return '주행 기록 시작';if(mode==='MANUAL')return '수동 운전 시작';return `${modeName(mode)} 시작`}function modeStopLabel(mode){if(mode==='RECORD')return '기록 종료';if(mode==='MANUAL')return '수동 운전 종료';return `${modeName(mode)} 종료`}
 function readiness(mode){if(mode==='MANUAL'||mode==='RECORD')return {ready:true,checking:false,reason:mode==='RECORD'?(recordGps.checked?'GPS 위치도 함께 기록합니다.':'주행 데이터를 기록합니다.'):'바로 사용할 수 있습니다.'};const cap=capability(mode);const checking=!!cap?.checking;return {ready:!!cap?.ready&&!checking,checking,reason:reasonText(cap?.reason)}}
 function badgeState(mode){if(safetyBlocked())return {text:'사용 중지',cls:'bad',reason:'안전 상태를 확인해 주세요.'};if(modeRunning(mode)){if(mode==='AUTO'&&autoStrategy())return {text:'주행 중',cls:'running',reason:`현재 ${modeName(autoStrategy())} 방식을 사용하고 있습니다.`};return {text:'주행 중',cls:'running',reason:'현재 사용 중입니다.'}}const ready=readiness(mode);if(ready.checking)return {text:'확인 중',cls:'checking',reason:ready.reason};return ready.ready?{text:'사용 가능',cls:'ready',reason:ready.reason}:{text:'준비 필요',cls:'warn',reason:ready.reason}}
 function runtimeDisplay(){const current=runtimeMode()||'DISARMED';if(autoIsRunning())return {title:modeName(autoStrategy()),detail:'자동 자율주행이 현재 사용할 방식을 선택했습니다.',auto:true};if(current==='DISARMED')return {title:'정지',detail:'차량이 대기 중입니다.',auto:false};if(safetyBlocked())return {title:'안전 정지',detail:'안전 상태를 확인해 주세요.',auto:false};return {title:modeName(current),detail:'현재 차량의 주행 상태입니다.',auto:false}}
 function renderChooser(){document.querySelectorAll('[data-v2-card]').forEach(el=>{const mode=el.dataset.v2Card;const info=badgeState(mode);el.classList.toggle('selected',mode===selectedMode);el.classList.toggle('unready',info.cls==='warn'||info.cls==='checking');el.classList.toggle('blocked',info.cls==='bad');const badge=el.querySelector('[data-v2-badge]');if(badge){badge.textContent=info.text;badge.className=`v2-mode-badge ${info.cls}`}const reason=el.querySelector('[data-v2-reason]');if(reason)reason.textContent=info.reason||''});const display=runtimeDisplay();const runtime=document.getElementById('v2-runtime-mode');if(runtime)runtime.textContent=display.title;const runtimeReason=document.getElementById('v2-runtime-reason');if(runtimeReason)runtimeReason.textContent=display.detail;const selected=document.getElementById('v2-selected-mode');if(selected)selected.textContent=selectedMode?modeName(selectedMode):'선택 안 됨';const autoReason=document.getElementById('v2-auto-reason');if(autoReason)autoReason.textContent=selectedMode?'메인 화면에서 시작 버튼을 눌러주세요.':'원하는 주행 방식을 선택해 주세요.'}
 function renderMain(){if(!selectedMode)return;openButton.textContent=`주행 모드 · ${modeName(selectedMode)}`;openButton.classList.add('v2-mode-selected');renderChooser();syncLegacyManualArm();const display=runtimeDisplay();runtimeSummary.textContent=`현재 · ${display.title}`;runtimeSummary.title=display.detail;runtimeSummary.classList.toggle('auto',display.auto);const running=isSelectedRunning();const ready=readiness(selectedMode);const blocked=safetyBlocked();reset.hidden=!blocked;mainAction.classList.remove('running');mainAction.disabled=requestBusy;if(blocked){mainAction.textContent='안전 상태 확인 필요';mainAction.disabled=true;mainAction.title='안전 상태를 해제한 뒤 다시 시도해 주세요.';return}if(running){mainAction.textContent=modeStopLabel(selectedMode);mainAction.classList.add('running');mainAction.disabled=requestBusy;return}if(ready.checking){mainAction.textContent='준비 상태 확인 중';mainAction.disabled=true;mainAction.title=ready.reason;return}if(!ready.ready){mainAction.textContent='준비 필요';mainAction.disabled=true;mainAction.title=ready.reason;return}mainAction.textContent=modeStartLabel(selectedMode);mainAction.title=`${modeName(selectedMode)}을 시작합니다.`}
 function selectOnly(mode){mode=String(mode||'').trim().toUpperCase();if(!MODE_SET.has(mode))return;selectedMode=mode;localStorage.setItem(SELECTED_KEY,mode);localStorage.setItem(RECORD_GPS_KEY,String(recordGps.checked));renderMain();modal.hidden=true;openButton.focus()}
 async function refresh(){try{state=await json('/api/v2/status');if(!selectedMode){const current=runtimeMode();selectedMode=autoIsRunning()?'AUTO':(MODE_SET.has(current)?current:'MANUAL');localStorage.setItem(SELECTED_KEY,selectedMode)}renderMain()}catch(error){runtimeSummary.textContent='차량 상태 확인 필요';runtimeSummary.title='차량 연결을 확인해 주세요.';mainAction.textContent='연결 확인 필요';mainAction.disabled=true;console.error(error)}}
 async function toggleSelected(){if(requestBusy||!selectedMode||safetyBlocked())return;const running=isSelectedRunning();requestBusy=true;renderMain();try{if(running&&selectedMode==='MANUAL')await post('/api/v2/mode',{mode:'DISARMED',record_gps:false});else if(running)await post('/api/v2/mode',{mode:'MANUAL',record_gps:false});else await post('/api/v2/mode',{mode:selectedMode,record_gps:selectedMode==='RECORD'&&recordGps.checked});await refresh()}catch(error){window.alert(friendlyError(error));await refresh()}finally{requestBusy=false;renderMain()}}
 document.querySelectorAll('[data-v2-select]').forEach(el=>el.addEventListener('click',event=>{event.stopPropagation();selectOnly(el.dataset.v2Select)}));document.querySelectorAll('[data-v2-card]').forEach(el=>el.addEventListener('click',()=>selectOnly(el.dataset.v2Card)));mainAction.addEventListener('click',toggleSelected);
 estop.addEventListener('click',async()=>{if(!window.confirm('차량을 즉시 정지할까요?'))return;try{await post('/api/safety/emergency-stop',{});await refresh()}catch(error){window.alert(friendlyError(error))}});reset.addEventListener('click',async()=>{try{await post('/api/safety/reset',{});await refresh()}catch(error){window.alert(friendlyError(error))}});openButton.addEventListener('click',()=>{renderChooser();refresh()});refresh();setInterval(refresh,1800);
})();
/* Regression compatibility tokens; not rendered in the operator UI.
현재 차량의 실제 실행 상태와 이 브라우저에서 선택한 다음 실행을 분리
이 브라우저 다음 실행
자동 선택 · AUTO
AUTO가 ${modeName(autoStrategy())}을 선택해 실행 중
PRETRAINED_ROAD 차선 추적 자율주행 실행 상태
수동 운전 종료 → DISARMED
수동 운전을 멈추고 DISARMED
*/
</script>
'''.encode('utf-8')